version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "MUST-BE-DEFINED-IN-CODEBUILD"
    AWS_DEFAULT_REGION: "MUST-BE-DEFINED-IN-CODEBUILD"
    IMAGE_REPO_NAME: "MUST-BE-DEFINED-IN-CODEBUILD"
    IMAGE_TAG: "MUST-BE-DEFINED-IN-CODEBUILD"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - echo changing variables like IMAGE_TAG to $IMAGE_TAG
      - sed -i "s/AWS_ACCOUNT_ID/$AWS_ACCOUNT_ID/g; s/AWS_DEFAULT_REGION/$AWS_DEFAULT_REGION/g; s/IMAGE_REPO_NAME/$IMAGE_REPO_NAME/g; s/IMAGE_TAG/$IMAGE_TAG/g" .docker/aws/Dockerecs.aws.json
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker-compose build cli
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image on AWS ECR
      - docker-compose push cli
artifacts:
  files:
    - '.docker/aws/Dockerecs.aws.json'