version: 0.2

env:
  git-credential-helper: yes
  variables:
    CODEBUILD_RESOLVED_SOURCE_VERSION: "NOT-SPECIFIED"
    IMAGE_TAG: "NOT-SPECIFIED"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - echo changing IMAGE_TAG to $IMAGE_TAG and BUILD_NUMBER to $CODEBUILD_BUILD_NUMBER
      - sed -i "s/IMAGE_TAG/$IMAGE_TAG/g; s/BUILD_NUMBER/$CODEBUILD_BUILD_NUMBER/g; s/AWS_REGION/$AWS_REGION/g" .docker/aws/Dockerecs.aws.json
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      # Build args are declared in docker-compose.yml
      - docker-compose -f docker-compose.yml build --pull
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image on $IMAGE_NAME:$IMAGE_TAG
      - docker-compose -f docker-compose.yml push
artifacts:
  files:
    - '.docker/aws/Dockerecs.aws.json'