version: "3.9"
services:
  fpm:
    image: 131826866465.dkr.ecr.${AWS_REGION}.amazonaws.com/devops-satis-app:${IMAGE_TAG:-dev}-${CODEBUILD_BUILD_NUMBER:-latest}
    build:
      context: .
      dockerfile: .docker/fpm/Dockerfile
  nginx:
    image: 131826866465.dkr.ecr.eu-west-1.amazonaws.com/docker-images:nginx1.22-fpm-alpine
    volumes_from:
     - fpm
    ports:
     - 8080:80
  cli:
    image: 131826866465.dkr.ecr.${AWS_REGION}.amazonaws.com/devops-satis-app:${IMAGE_TAG:-dev}-${CODEBUILD_BUILD_NUMBER:-latest}
    command: ["crond","-f","-L","/var/log/crond.log"]