version: "3.9"
services:
  cli:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}
    build:
      context: .
      dockerfile: .docker/cli/Dockerfile
      args:
        - AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
        - AWS_REGION=${AWS_DEFAULT_REGION}
        - IMAGE_TAG=php8.2-apache-alpine
