version: "3.9"
services:
  fpm:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}-${CODEBUILD_BUILD_NUMBER:-latest}
    build:
      context: .
      dockerfile: .docker/fpm/Dockerfile
      args:
        - AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
        - AWS_REGION=${AWS_DEFAULT_REGION}

  nginx:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/docker-images:nginx1.24-alpine
    ports:
      - 8080:80
    volumes_from:
      - fpm
